---
- hosts: all
  handlers:
    - name: reload systemd
      command: /bin/systemctl daemon-reload

    - name: restart systemd-journald
      service:
        name: systemd-journald
        state: restarted

    - name: restart nginx
      service:
        name: nginx
        state: restarted

    - name: restart php7.4-fpm
      service:
        name: php7.4-fpm
        state: restarted

    - name: restart mysql
      service:
        name: mysql
        state: restarted

  tasks:
    - name: Falhar se não estiver sendo executado no Ubuntu
      fail:
        msg: Este manual só funciona em sistemas Ubuntu!
      when: ansible_distribution != 'Ubuntu'
      tags: always

    - name: Falhar se o Ubuntu for anterior a versão 20.04
      fail:
        msg: Este manual requer o Ubuntu >= 20.04
      when: ansible_distribution_major_version|int < 20
      tags: always

    - name: Verificando o nome/versão do pacote PHP disponível
      shell: apt-cache show php-fpm | grep Depends | head | awk '{print $2}'
      register: php_version_query
      changed_when: False
      tags: always

    - name: Registrando o nome/versão do pacote PHP disponível
      set_fact:
        # e.g.: php7.3-fpm
        php_fpm_package_name: "{{ php_version_query.stdout }}"
        # e.g.: php7.3
        php_version: "{{ php_version_query.stdout.split('-')[0] }}"
        # e.g.: 7.3
        php_version_number: "{{ php_version_query.stdout.split('-')[0][3:] }}"
      tags: always

    - include: tasks/systemd.yml
      tags:
        - default
        - systemd

    - include: tasks/general.yml
      tags:
        - default
        - general

    - include: tasks/mysql.yml
      tags:
        - default
        - mysql

    - include: tasks/php-fpm.yml
      tags:
        - default
        - php-fpm

    - include: tasks/nginx.yml
      tags:
        - default
        - nginx

    - include: tasks/phpmyadmin.yml
      tags:
        - default
        - pma

    - include: tasks/tfs.yml
      tags:
        - default
        - tfs

    - include: tasks/znoteaac.yml
      tags:
        - default
        - znote

    - include: tasks/general-last.yml
      tags:
        - default
        - general

    - include: tasks/wine.yml
      tags: wine
