---
- name: Instalando o debconf para definir informações pré-configuradas
  apt:
    pkg: debconf-utils

- name: Definindo as informações predefinidas phpmyadmin/dbconfig-install
  debconf:
    name: phpmyadmin
    question: phpmyadmin/dbconfig-install
    value: true
    vtype: boolean

- name: Definindo as informações predefinidas phpmyadmin/app-password-confirm
  debconf:
    name: phpmyadmin
    question: phpmyadmin/app-password-confirm
    value: ''
    vtype: password

- name: Definir informações predefinidas phpmyadmin/mysql/admin-pass
  debconf:
    name: phpmyadmin
    question: phpmyadmin/mysql/admin-pass
    value: ''
    vtype: password

- name: Definindo as informações predefinidas phpmyadmin/mysql/app-pass
  debconf:
    name: phpmyadmin
    question: phpmyadmin/mysql/app-pass
    value: ''
    vtype: password

- name: Definindo as informações predefinidas phpmyadmin/reconfigure-webserver
  debconf:
    name: phpmyadmin
    question: phpmyadmin/reconfigure-webserver
    value: ''
    vtype: multiselect

- name: Instalando o phpmyadmin
  apt:
    pkg: phpmyadmin
    state: latest
