---
- name: Instalando os pacotes necessários para compilar o TFS
  apt:
    state: latest
    pkg:
      - git
      - cmake
      - build-essential
      - libmysqlclient-dev
      - libboost-system-dev
      - libboost-date-time-dev
      - libboost-filesystem-dev
      - libboost-iostreams-dev
      - libcrypto++-dev
      - liblua5.2-dev
      - libluajit-5.1-dev
      - libpugixml-dev
      - libfmt-dev

- name: Instalando o serviço systemd para TFS
  template:
    src: templates/{{item}}
    dest: /etc/systemd/system/{{item}}
  with_items:
    - tfs.service
    - tfs-gdb.service

- name: Baixando o TFS mais recente do github
  git:
    repo: https://github.com/otland/forgottenserver.git
    dest: /home/otsmanager/forgottenserver
    version: "1.4"
  become: true
  become_user: otsmanager

- name: Analisando o config.lua existente
  shell: grep -s mysqlPass /home/otsmanager/forgottenserver/config.lua | sed -E 's/mysqlPass = "(.*)"/\1/g'
  register: existingpass

- name: Gerando uma senha aleatória do servidor de autenticação MySQL
  command: openssl rand -base64 18
  register: randompass
  when: not existingpass.stdout

- set_fact:
    mysql_forgottenserver_pass: "{{ randompass.stdout if randompass is not skipped else existingpass.stdout }}"

- name: Criando um usuário de banco de dados para TFS
  mysql_user:
    name: forgottenserver
    password: "{{mysql_forgottenserver_pass}}"
    priv: forgottenserver.*:ALL
    check_implicit_admin: yes

- name: Criando um banco de dados para TFS
  mysql_db:
    name: forgottenserver

- name: Importando um banco de dados para TFS
  mysql_db:
    name: forgottenserver
    state: import
    target: /home/otsmanager/forgottenserver/schema.sql

- name: Copiando config.lua.dist para config.lua se necessário
  copy:
    dest: /home/otsmanager/forgottenserver/config.lua
    src: /home/otsmanager/forgottenserver/config.lua.dist
    remote_src: yes
    owner: otsmanager
    group: otsmanager

- name: Colocando o mysqlHost do banco de dados em config.lua
  lineinfile:
    dest: /home/otsmanager/forgottenserver/config.lua
    regexp: ^mysqlHost
    line: 'mysqlHost = "localhost"'

- name: Coloquando o mysqlSock do banco de dados em config.lua
  lineinfile:
    dest: /home/otsmanager/forgottenserver/config.lua
    regexp: ^mysqlSock
    line: 'mysqlSock = "/var/run/mysqld/mysqld.sock"'

- name: Colocando a senha do banco de dados em config.lua
  lineinfile:
    dest: /home/otsmanager/forgottenserver/config.lua
    regexp: ^mysqlPass
    line: 'mysqlPass = "{{mysql_forgottenserver_pass}}"'

- name: Colocando o endereço IP do servidor em config.lua
  lineinfile:
    dest: /home/otsmanager/forgottenserver/config.lua
    regexp: "^ip ="
    line: 'ip = "{{ansible_default_ipv4.address}}"'

- name: Criando um diretório de construção BUILD
  file:
    path: /home/otsmanager/forgottenserver/build
    owner: otsmanager
    group: otsmanager
    mode: 0755
    state: directory
  become: true
  become_user: otsmanager

- name: Cmake do código fonte do TFS
  command: cmake ..
  args:
    chdir: /home/otsmanager/forgottenserver/build
  tags: compile
  become: true
  become_user: otsmanager

- name: Compilando código fonte do TFS
  command: make -j2
  args:
    chdir: /home/otsmanager/forgottenserver/build
  tags: compile
  become: true
  become_user: otsmanager
